### ISSUE TITLE
Code need key to work?

### ISSUE THREAD

**Issue by fasdasdasdassdd** [martani/Padding-Oracle-Attack#3]
Hi,
For some reason your code dosent work if you dont have the correct key.
If you remove the real key and replace it with a invalid key the result is going to be wrong. So than the attach is pointless if you have to now the key to attach. Maby i am just being stupid and does something wrong? Maby i use the code wrong, if so please show me how to use it correcly.. :)

**Comment by martani** [comment]
What's the issue exactly? Did you run the test in: https://github.com/martani/Padding-Oracle-Attack/blob/master/PaddingOracleAttackTest/Main.cs ?

The attacker does not need to know about any encryption keys, all it needs is an endpoint that supports AES CBC mode. See the online Oracle in: https://github.com/martani/Padding-Oracle-Attack/blob/master/PaddingOracleAttackTest/Oracles/OnlineCBCOracle.cs

**Comment by fasdasdasdassdd** [comment]
Your RequestOracle (byte[] cipher) function use the key you used to encrypt the message to decrypt the message under the attach. If you replace the key your attach aren't going to work. (After my understanding)

Hope it is me doing something wrong xD
Just to test can you decrypt this message? 
`020302030203020302020202020202023B668C98C64F67C43A56FBCE7B8E150E9D2B1F3669584BBFEE4D8A0E189ECC9A`

`02030203020302030202020202020202` is the iv 😃 

Thank you for the answer.
keep up the good work <3

**Comment by martani** [comment]
I don't think you understand what's going on here. The oracle obviously has access to the private key, that's how it decrypts the payload and returns true or false if the padding is correct or not.

The attacker on the other hand has no knowledge of the key, and only uses the true/false response from the oracle to decrypt the cipher.

This oracle interface for example (which I already mentioned in the previous comment) is only sending a http request, no knowledge of keys whatsoever.

**Comment by fasdasdasdassdd** [comment]
The attacker doesn't have the key. Thats the point, out from what i have tested your program doesn't get the right text if you are trying to decrypt a message without the real key.

`020302030203020302020202020202023B668C98C64F67C43A56FBCE7B8E150E9D2B1F3669584BBFEE4D8A0E189ECC9A` This should be all the info a attacker needs to perform a padding oracle attack and get the plain text.

**Comment by martani** [comment]
Where did that cipher text come from? Do you have the oracle that generated that cipher? Do you have code i can help you with?

**Comment by fasdasdasdassdd** [comment]
yeah, that had been really nice have been trying to implement an attack for weeks now xD But no luck.

This is the oracle: [https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndaelmanaged.createdecryptor?view=netframework-4.8](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndaelmanaged.createdecryptor?view=netframework-4.8)

Microsoft haw said it is vulnerable to a attach. [https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode](https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode)
Had been wery nice if you could help me 👍

**Comment by fasdasdasdassdd** [comment]
You will get the same cipher text using the oracle you used. (If you have the same key and iv of course) 😄 <3

**Comment by martani** [comment]
You need to read up more on what's the attack and how it's done. You can't just throw some cipher at this library and expect it to decrypt it.

In a nutshell, you need an oracle (a web server, some process etc) that has access to a private key to decrypt the cipher. But it leaks information while decrypting the cipher saying if the *padding* was correct or not during the decryption.

The attacker in this library uses that leaked info about padding to decrypt the cipher, without any access to the private key.

**Comment by fasdasdasdassdd** [comment]
You need to use a fake key for this, sins you dont have the encryption key.
Than you do a padding oracle attack finding the bytes.
It should be possible, it is the point of the attach. xD

**Comment by fasdasdasdassdd** [comment]
It is how it is, 
You dont know the key, the key is secret. 
So how can you can solve this?? `020302030203020302020202020202023B668C98C64F67C43A56FBCE7B8E150E9D2B1F3669584BBFEE4D8A0E189ECC9A `

**Comment by fasdasdasdassdd** [comment]
Thare is a way i need just to figure out how

**Comment by fasdasdasdassdd** [comment]
Lel

**Comment by fasdasdasdassdd** [comment]
???

**Comment by fasdasdasdassdd** [comment]
???????
